import { Playfair_Display, Quicksand } from "next/font/google";

import "./globals.css";

const playfairDisplay = Playfair_Display({
  subsets: ["latin-ext"],
  weight: "700",
  variable: "--font-playfair-display",
});
const quicksand = Quicksand({
  subsets: ["latin-ext"],
  weight: "400",
  variable: "--font-quicksand",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.className} bg-night-blue text-mage-silver`}
      >
        {children}
      </body>
    </html>
  );
}
